# Generated by Django 2.0.2 on 2018-02-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicechart',
            name='device',
            field=models.IntegerField(),
        ),
    ]
