# Generated by Django 2.0.2 on 2018-02-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20180215_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicechart',
            name='device',
            field=models.IntegerField(db_index=True),
        ),
    ]
