# Generated by Django 2.0.2 on 2018-02-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_auto_20180216_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ip_addr',
            field=models.CharField(blank=True, default=None, max_length=45, null=True),
        ),
    ]
