# Generated by Django 2.0.2 on 2018-02-19 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interface', '0006_auto_20180216_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
        migrations.AddField(
            model_name='device',
            name='users',
            field=models.ManyToManyField(db_index=True, default=(), to=settings.AUTH_USER_MODEL),
        ),
    ]
