# Generated by Django 2.0.2 on 2018-02-19 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_auto_20180219_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='users',
            field=models.ManyToManyField(db_index=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
